insert into class (title, difficulty) values ('A dive into Data Quality Services' ,'Intermediate');
insert into class (title, difficulty) values ('A Dynamic World Demands Dynamic SQL' ,'Intermediate');
insert into class (title, difficulty) values ('A Dynamic World Demands Dynamic SQL' ,'Intermediate');
insert into class (title, difficulty) values ('Absolute Introductory Session on SQL Server 2014 In-Memory Optimized Databases (Hekaton)' ,'Beginner');
insert into class (title, difficulty) values ('AlwaysOn: Improve reliability and reporting performance with one cool tech' ,'Beginner');
insert into class (title, difficulty) values ('An introduction to Data Mining' ,'Intermediate');
insert into class (title, difficulty) values ('An Introduction to Database Design' ,'Beginner');
insert into class (title, difficulty) values ('Autogenerating a process data warehouse' ,'Advanced');
insert into class (title, difficulty) values ('Automate your daily checklist with PBM and CMS' ,'Intermediate');
insert into class (title, difficulty) values ('Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters' ,'Intermediate');
insert into class (title, difficulty) values ('Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters' ,'Intermediate');
insert into class (title, difficulty) values ('Automating Execution Plan Analysis' ,'Advanced');
insert into class (title, difficulty) values ('Automating Execution Plan Analysis' ,'Advanced');
insert into class (title, difficulty) values ('Automating SQL Server using PowerShell' ,'Intermediate');
insert into class (title, difficulty) values ('Balanced Scorecards using SSRS' ,'Intermediate');
insert into class (title, difficulty) values ('Baselines and Performance Monitoring with PAL' ,'Beginner');
insert into class (title, difficulty) values ('Basic Database Design' ,'Beginner');
insert into class (title, difficulty) values ('Basic Database Programming' ,'Beginner');
insert into class (title, difficulty) values ('Become a BI Independent Consultant!' ,'Beginner');
insert into class (title, difficulty) values ('Becoming a Top DBA--Learning Automation in SQL Server' ,'Beginner');
insert into class (title, difficulty) values ('Best Practices Document' ,'Intermediate');
insert into class (title, difficulty) values ('Best Practices for Efficient SSRS Report Creation' ,'Beginner');
insert into class (title, difficulty) values ('Biggest Loser: Database Edition' ,'Intermediate');
insert into class (title, difficulty) values ('Building a BI Solution in the Cloud' ,'Intermediate');
insert into class (title, difficulty) values ('Building an Effective Data Warehouse Architecture' ,'Beginner');
insert into class (title, difficulty) values ('Building an Effective Data Warehouse Architecture with the cloud and MPP' ,'Beginner');
insert into class (title, difficulty) values ('Bulk load and minimal logged inserts' ,'Advanced');
insert into class (title, difficulty) values ('Business Analytics with SQL Server & Power Map:Everything you want to know but were afraid to ask' ,'Intermediate');
insert into class (title, difficulty) values ('Challenges to designing financial warehouses, lessons learnt' ,'Intermediate');
insert into class (title, difficulty) values ('Change Data Capture in SQL Server 2008/2012' ,'Intermediate');
insert into class (title, difficulty) values ('Changing Your Habits to Improve the Performance of Your T-SQL' ,'Beginner');
insert into class (title, difficulty) values ('Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments' ,'Beginner');
insert into class (title, difficulty) values ('Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments' ,'Non-Technical');
insert into class (title, difficulty) values ('Coffee Break' ,'Non-Technical');
insert into class (title, difficulty) values ('Creating A Performance Health Repository - using MDW' ,'Beginner');
insert into class (title, difficulty) values ('Creating efficient and effective SSRS BI Solutions' ,'Intermediate');
insert into class (title, difficulty) values ('Creating efficient and effective SSRS BI Solutions' ,'Intermediate');
insert into class (title, difficulty) values ('Data Partitioning' ,'Intermediate');
insert into class (title, difficulty) values ('Data Tier Application Testing with NUnit and Distributed Replay' ,'Intermediate');
insert into class (title, difficulty) values ('Database design for mere developers' ,'Intermediate');
insert into class (title, difficulty) values ('Database design for mere developers' ,'Intermediate');
insert into class (title, difficulty) values ('Database Design: Solving Problems Before they Start!' ,'Beginner');
insert into class (title, difficulty) values ('Database Modeling and Design' ,'Intermediate');
insert into class (title, difficulty) values ('Database Virtualization and Drinking out of the Fire Hose' ,'Intermediate');
insert into class (title, difficulty) values ('DAX and the tabular model' ,'Intermediate');
insert into class (title, difficulty) values ('DBA FOR DUMMIES' ,'Beginner');
insert into class (title, difficulty) values ('Dealing With Difficult People' ,'Beginner');
insert into class (title, difficulty) values ('Development Lifecycle with SQL Server Data Tools and DACFx' ,'Intermediate');
insert into class (title, difficulty) values ('Did You Vote Today? A DBAs Guide to Cluster Quorum' ,'Advanced');
insert into class (title, difficulty) values ('Dimensional Modeling Design Patterns: Beyond Basics' ,'Intermediate');
insert into class (title, difficulty) values ('Dimensional Modeling Design Patterns: Beyond Basics' ,'Intermediate');
insert into class (title, difficulty) values ('Diving Into Query Execution Plans' ,'Intermediate');
insert into class (title, difficulty) values ('Dynamic SQL: Writing Efficient Queries on the Fly' ,'Beginner');
insert into class (title, difficulty) values ('Easy Architecture Design for HA and DR' ,'Intermediate');
insert into class (title, difficulty) values ('Enhancing your career: Building your personal brand' ,'Beginner');
insert into class (title, difficulty) values ('Establishing a SLA' ,'Intermediate');
insert into class (title, difficulty) values ('ETL not ELT! Common mistakes and misconceptions about SSIS' ,'Advanced');
insert into class (title, difficulty) values ('Event Kickoff and Networking' ,'Non-Technical');
insert into class (title, difficulty) values ('Execution Plans: What Can You Do With Them?' ,'Intermediate');
insert into class (title, difficulty) values ('Faster, Better Decisions with Self Service Business Analytics' ,'Intermediate');
insert into class (title, difficulty) values ('Full Text Indexing Basics' ,'Beginner');
insert into class (title, difficulty) values ('Get your Mining Model Predictions out to all' ,'Intermediate');
insert into class (title, difficulty) values ('Getting a job with Microsoft' ,'Non-Technical');
insert into class (title, difficulty) values ('Graph Databases for SQL Server Professionals' ,'Intermediate');
insert into class (title, difficulty) values ('Hacking Exposé - Using SSL to Protect SQL Connections' ,'Intermediate');
insert into class (title, difficulty) values ('Hacking the SSIS 2012 Catalog' ,'Beginner');
insert into class (title, difficulty) values ('Hidden in plain sight: master your tools' ,'Intermediate');
insert into class (title, difficulty) values ('Highly Available SQL Server in Windows Azure IaaS' ,'Intermediate');
insert into class (title, difficulty) values ('How to Make a LOT More Money as a Consultant' ,'Beginner');
insert into class (title, difficulty) values ('How to Think Like the Engine' ,'Intermediate');
insert into class (title, difficulty) values ('Hybrid Cloud Scenarios with SQL Server 2014' ,'Intermediate');
insert into class (title, difficulty) values ('Hybrid Solutions: The Future of SQL Server Disaster Recovery' ,'Intermediate');
insert into class (title, difficulty) values ('Implementing Data Warehouse Patterns with the Microsoft BI Tools' ,'Intermediate');
insert into class (title, difficulty) values ('Inroduction to Triggers' ,'Beginner');
insert into class (title, difficulty) values ('Integrating Reporting Services with SharePoint' ,'Intermediate');
insert into class (title, difficulty) values ('Integration Services (SSIS) for the DBA' ,'Intermediate');
insert into class (title, difficulty) values ('Introducing Power BI' ,'Beginner');
insert into class (title, difficulty) values ('Introduction to Database Recovery' ,'Beginner');
insert into class (title, difficulty) values ('Introduction to High Availability with SQL Server' ,'Beginner');
insert into class (title, difficulty) values ('Introduction to Powershell for DBA''s' ,'Beginner');
insert into class (title, difficulty) values ('Introduction to SQL Server - Part 1' ,'Beginner');
insert into class (title, difficulty) values ('Introduction to SQL Server - Part 2' ,'Beginner');
insert into class (title, difficulty) values ('Is That A Failover Cluster On Your Laptop/Desktop?' ,'Intermediate');
insert into class (title, difficulty) values ('Leaving the Windows Open' ,'Intermediate');
insert into class (title, difficulty) values ('Lunch Break' ,'Non-Technical');
insert into class (title, difficulty) values ('Lunchtime Keynote' ,'Non-Technical');
insert into class (title, difficulty) values ('Master Data Services Best Practices' ,'Intermediate');
insert into class (title, difficulty) values ('Master Data Services Disaster Recovery' ,'Intermediate');
insert into class (title, difficulty) values ('Mind your language!! Cursors are a dirty word' ,'Intermediate');
insert into class (title, difficulty) values ('Modern Data Warehousing' ,'Beginner');
insert into class (title, difficulty) values ('Monitoring Server health via Reporting Services dashboards' ,'Intermediate');
insert into class (title, difficulty) values ('Monitoring SQL Server using Extended Events' ,'Beginner');
insert into class (title, difficulty) values ('Multidimensional vs Tabular - May the Best Model Win' ,'Intermediate');
insert into class (title, difficulty) values ('Murder They Wrote' ,'Intermediate');
insert into class (title, difficulty) values ('Never Have to Say "Mayday!!!" Again' ,'Beginner');
insert into class (title, difficulty) values ('Now you see it! Now you don’t! Conjuring many reports utilizing only one SSRS report.' ,'Intermediate');
insert into class (title, difficulty) values ('Optimal Infrastructure Strategies for Cisco UCS, Nexus and SQL Server' ,'Non-Technical');
insert into class (title, difficulty) values ('Optimizing Protected Indexes' ,'Intermediate');
insert into class (title, difficulty) values ('Partitioning as a design pattern' ,'Advanced');
insert into class (title, difficulty) values ('Power BI Components in Microsoft''s Self-Service BI Suite' ,'Beginner');
insert into class (title, difficulty) values ('Power to the people!!' ,'Intermediate');
insert into class (title, difficulty) values ('PowerShell Basics for SQLServer' ,'Beginner');
insert into class (title, difficulty) values ('PowerShell for the Reluctant DBA / Developer' ,'Beginner');
insert into class (title, difficulty) values ('Prevent Recovery Amnesia – Forget the Backups' ,'Beginner');
insert into class (title, difficulty) values ('Query Optimization Crash Course' ,'Beginner');
insert into class (title, difficulty) values ('Raffle' ,'Non-Technical');
insert into class (title, difficulty) values ('Rapid Application Development with Master Data Services' ,'Intermediate');
insert into class (title, difficulty) values ('Recovery and Backup for Beginners' ,'Beginner');
insert into class (title, difficulty) values ('Reduce, Reuse, Recycle: Automating Your BI Framework' ,'Intermediate');
insert into class (title, difficulty) values ('Registrations' ,'Non-Technical');
insert into class (title, difficulty) values ('Replicaton Technologies' ,'Advanced');
insert into class (title, difficulty) values ('Reporting Services for Mere DBAs' ,'Intermediate');
insert into class (title, difficulty) values ('Scaling with SQL Server Service Broker' ,'Advanced');
insert into class (title, difficulty) values ('Scaling with SQL Server Service Broker' ,'Advanced');
insert into class (title, difficulty) values ('Self-Service Data Integration with Power Query' ,'Beginner');
insert into class (title, difficulty) values ('Shortcuts to Building SSIS in .Net' ,'Beginner');
insert into class (title, difficulty) values ('So You Want To Be A Consultant?' ,'Beginner');
insert into class (title, difficulty) values ('SQL anti patterns' ,'Advanced');
insert into class (title, difficulty) values ('SQL Server 2012/2014 Columnstore index' ,'Intermediate');
insert into class (title, difficulty) values ('SQL Server 2012/2014 Performance Tuning All Up' ,'Intermediate');
insert into class (title, difficulty) values ('SQL Server 2014 Data Access Layers' ,'Intermediate');
insert into class (title, difficulty) values ('SQL Server 2014 New Features' ,'Intermediate');
insert into class (title, difficulty) values ('SQL Server AlwaysOn Availability Groups' ,'Beginner');
insert into class (title, difficulty) values ('SQL Server and the Cloud' ,'Beginner');
insert into class (title, difficulty) values ('SQL Server Compression and what it can do for you' ,'Advanced');
insert into class (title, difficulty) values ('SQL Server Reporting Services 2014 on Steroids!!' ,'Intermediate');
insert into class (title, difficulty) values ('SQL Server Reporting Services Best Practices' ,'Intermediate');
insert into class (title, difficulty) values ('SQL Server Reporting Services, attendees choose' ,'Intermediate');
insert into class (title, difficulty) values ('SQL Server Storage Engine under the hood' ,'Intermediate');
insert into class (title, difficulty) values ('SQL Server Storage internals: Looking under the hood.' ,'Advanced');
insert into class (title, difficulty) values ('SSIS 2014 Data Flow Tuning Tips and Tricks' ,'Beginner');
insert into class (title, difficulty) values ('Standalone to High-Availability Clusters over Lunch—with Time to Spare' ,'Intermediate');
insert into class (title, difficulty) values ('Stress testing SQL Server' ,'Advanced');
insert into class (title, difficulty) values ('Table partitioning for Azure SQL Databases' ,'Beginner');
insert into class (title, difficulty) values ('Testing' ,'Beginner');
insert into class (title, difficulty) values ('The future of the data professional' ,'Beginner');
insert into class (title, difficulty) values ('The Quest for the Golden Record:MDM Best Practices' ,'Beginner');
insert into class (title, difficulty) values ('The Quest to Find Bad Data With Data Profiling' ,'Intermediate');
insert into class (title, difficulty) values ('The Spy Who Loathed Me - An Intro to SQL Security' ,'Beginner');
insert into class (title, difficulty) values ('Tired of the CRUD? Automate it!' ,'Intermediate');
insert into class (title, difficulty) values ('Top 5 Ways to Improve Your triggers' ,'Intermediate');
insert into class (title, difficulty) values ('Tricks that have saved my bacon' ,'Beginner');
insert into class (title, difficulty) values ('T-SQL : Bad Habits & Best Practices' ,'Beginner');
insert into class (title, difficulty) values ('T-SQL for Application Developers - Attendees chose' ,'Intermediate');
insert into class (title, difficulty) values ('Tune Queries By Fixing Bad Parameter Sniffing' ,'Intermediate');
insert into class (title, difficulty) values ('Using Extended Events in SQL Server' ,'Advanced');
insert into class (title, difficulty) values ('Watch Brent Tune Queries' ,'Intermediate');
insert into class (title, difficulty) values ('What every SQL Server DBA needs to know about Windows Server 10 Technical Preview' ,'Intermediate');
insert into class (title, difficulty) values ('What exactly is big data and why should I care?' ,'Beginner');
insert into class (title, difficulty) values ('What is it like to work for Microsoft?' ,'Beginner');
insert into class (title, difficulty) values ('What’s new in SQL Server Integration Services 2012' ,'Intermediate');
insert into class (title, difficulty) values ('Why do we shun using tools for DBA job?' ,'Intermediate');
insert into class (title, difficulty) values ('Why OLAP? Building SSAS cubes and benefits of OLAP' ,'Intermediate');
insert into class (title, difficulty) values ('You''re Doing It Wrong!!' ,'Intermediate');
