Insert into address (address,city, zip,state) VALUES ('10 Napa Ct.','Lebanon','2450','Oregon');
Insert into address (address,city, zip,state) VALUES ('1000 Bidweld Street','Haney','98371','British Columbia');
Insert into address (address,city, zip,state) VALUES ('1002 N. Spoonwood Court','Hervey Bay','PB12','Queensland');
Insert into address (address,city, zip,state) VALUES ('1003 Matterhorn Ct','Lebanon','21201','Oregon');
Insert into address (address,city, zip,state) VALUES ('1005 Matterhorn Ct.','Cambridge','94704','England');
Insert into address (address,city, zip,state) VALUES ('1005 Matterhorn Ct.','Mill Valley','V7L 4J4','California');
Insert into address (address,city, zip,state) VALUES ('1005 Tanager Court','Corvallis','98312','Oregon');
Insert into address (address,city, zip,state) VALUES ('1005 Tanager Court','Milsons Point','GA10','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1006 Deercreek Ln','Bellflower','V9','California');
Insert into address (address,city, zip,state) VALUES ('1006 Deercreek Ln','Torrance','94704','California');
Insert into address (address,city, zip,state) VALUES ('101 Adobe Dr','Coffs Harbour','98168','New South Wales');
Insert into address (address,city, zip,state) VALUES ('101 Adobe Dr','Puyallup','SW8 4BG','Washington');
Insert into address (address,city, zip,state) VALUES ('101, avenue de la Gare','Peterborough','90401','England');
Insert into address (address,city, zip,state) VALUES ('1010 Maple','Baltimore','98312','Maryland');
Insert into address (address,city, zip,state) VALUES ('1011 Yolanda Circle','Berkeley','2036','California');
Insert into address (address,city, zip,state) VALUES ('1011 Yolanda Circle','N. Vancouver','95062','British Columbia');
Insert into address (address,city, zip,state) VALUES ('1013 Holiday Hills Dr.','Bremerton','97355','Washington');
Insert into address (address,city, zip,state) VALUES ('1013 Holiday Hills Dr.','Gateshead','94014','England');
Insert into address (address,city, zip,state) VALUES ('1015 Lynwood Drive','Metchosin','LE18','British Columbia');
Insert into address (address,city, zip,state) VALUES ('1019 Carletto Drive','Berkeley','98033','California');
Insert into address (address,city, zip,state) VALUES ('1019 Mt. Davidson Court','Burien','97045','Washington');
Insert into address (address,city, zip,state) VALUES ('1019 Mt. Davidson Court','London','91910','England');
Insert into address (address,city, zip,state) VALUES ('102 Vista Place','Santa Monica','97045','California');
Insert into address (address,city, zip,state) VALUES ('1020 Book Road','Bremerton','AS23','Washington');
Insert into address (address,city, zip,state) VALUES ('1020 Carletto Drive','Matraville','91791','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1020 Carletto Drive','Santa Cruz','2777','California');
Insert into address (address,city, zip,state) VALUES ('1023 Hawkins Street','Lebanon','97205','Oregon');
Insert into address (address,city, zip,state) VALUES ('1024 Walnut Blvd.','Colma','2264','California');
Insert into address (address,city, zip,state) VALUES ('1025 Holly Oak Drive','Leeds','W1X3SE','England');
Insert into address (address,city, zip,state) VALUES ('1025 R St.','Kirkland','45202','Washington');
Insert into address (address,city, zip,state) VALUES ('1025 Yosemite Dr.','Oregon City','90505','Oregon');
Insert into address (address,city, zip,state) VALUES ('1028 Green View Court','Chula Vista','4810','California');
Insert into address (address,city, zip,state) VALUES ('1028 Green View Court','Oregon City','2055','Oregon');
Insert into address (address,city, zip,state) VALUES ('1037 Hayes Court','Stoke-on-Trent','4655','England');
Insert into address (address,city, zip,state) VALUES ('1039 Adelaide St.','West Covina','99362','California');
Insert into address (address,city, zip,state) VALUES ('104 Hilltop Dr.','Springwood','2500','New South Wales');
Insert into address (address,city, zip,state) VALUES ('104 Kaski Ln.','Portland','2444','Oregon');
Insert into address (address,city, zip,state) VALUES ('1040 Greenbush Drive','Silverwater','98225','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1040 Northridge Road','London','W10 6BL','England');
Insert into address (address,city, zip,state) VALUES ('1044 San Carlos','Cincinnati','98104','Ohio');
Insert into address (address,city, zip,state) VALUES ('1045 Lolita Drive','Torrance','90012','California');
Insert into address (address,city, zip,state) VALUES ('1045 Lolita Drive','Townsville','98201','Queensland');
Insert into address (address,city, zip,state) VALUES ('1047 Las Quebradas Lane','North Sydney','94704','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1048 Burwood Way','Hervey Bay','94014','Queensland');
Insert into address (address,city, zip,state) VALUES ('1048 Las Quebradas Lane','Walla Walla','V3A 4R2','Washington');
Insert into address (address,city, zip,state) VALUES ('1048 Las Quebradas Lane','Wollongong','SW6 SBY','New South Wales');
Insert into address (address,city, zip,state) VALUES ('105 Clark Creek Lane','Port Macquarie','92020','New South Wales');
Insert into address (address,city, zip,state) VALUES ('105 Woodruff Ln.','Bellingham','91502','Washington');
Insert into address (address,city, zip,state) VALUES ('1050 Creed Ave','London','98052','England');
Insert into address (address,city, zip,state) VALUES ('081, boulevard du Montparnasse','Seattle','98225','Washington');
Insert into address (address,city, zip,state) VALUES ('1 Smiling Tree Court','Los Angeles','2444','California');
Insert into address (address,city, zip,state) VALUES ('100, rue des Rosiers','Everett','98901','Washington');
Insert into address (address,city, zip,state) VALUES ('1002 N. Spoonwood Court','Berkeley','91502','California');
Insert into address (address,city, zip,state) VALUES ('1005 Fremont Street','Colma','2138','California');
Insert into address (address,city, zip,state) VALUES ('1005 Valley Oak Plaza','Langley','91364','British Columbia');
Insert into address (address,city, zip,state) VALUES ('1005 Valley Oak Plaza','London','2450','England');
Insert into address (address,city, zip,state) VALUES ('1007 Cardinet Dr.','El Cajon','98284','California');
Insert into address (address,city, zip,state) VALUES ('1008 Lydia Lane','Burbank','97034','California');
Insert into address (address,city, zip,state) VALUES ('101 Candy Rd.','Redmond','98270','Washington');
Insert into address (address,city, zip,state) VALUES ('1011 Green St.','Bellingham','MK8 8DF','Washington');
Insert into address (address,city, zip,state) VALUES ('1013 Buchanan Rd','Port Macquarie','T2P 2G8','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1013 Buchanan Rd','Yakima','4810','Washington');
Insert into address (address,city, zip,state) VALUES ('1016 Park Avenue','Burbank','91502','California');
Insert into address (address,city, zip,state) VALUES ('1019 Book Road','Rhodes','OX1','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1019 Buchanan Road','Woodland Hills','4810','California');
Insert into address (address,city, zip,state) VALUES ('1019 Candy Rd.','Coffs Harbour','98036','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1019 Chance Drive','Sedro Woolley','3205','Washington');
Insert into address (address,city, zip,state) VALUES ('1019 Kenwal Rd.','Lake Oswego','98027','Oregon');
Insert into address (address,city, zip,state) VALUES ('1019 Pennsylvania Blvd','Marysville','3280','Washington');
Insert into address (address,city, zip,state) VALUES ('102 Vista Place','Milton Keynes','94010','England');
Insert into address (address,city, zip,state) VALUES ('10203 Acorn Avenue','Calgary','98168','Alberta');
Insert into address (address,city, zip,state) VALUES ('1023 Hawkins Street','Townsville','98501','Queensland');
Insert into address (address,city, zip,state) VALUES ('1023 Riveria Way','Burbank','PE17','California');
Insert into address (address,city, zip,state) VALUES ('1023 Riviera Way','Oxford','2113','England');
Insert into address (address,city, zip,state) VALUES ('1025 Yosemite Dr.','Townsville','AS23','Queensland');
Insert into address (address,city, zip,state) VALUES ('1026 Mt. Wilson Pl.','Lynnwood','92102','Washington');
Insert into address (address,city, zip,state) VALUES ('1026 Mt. Wilson Pl.','South Melbourne','98366','Victoria');
Insert into address (address,city, zip,state) VALUES ('1028 Indigo Ct.','Issaquah','2444','Washington');
Insert into address (address,city, zip,state) VALUES ('1028 Indigo Ct.','Warrnambool','94519','Victoria');
Insert into address (address,city, zip,state) VALUES ('1028 Royal Oak Rd.','Burlingame','V2L3W8','California');
Insert into address (address,city, zip,state) VALUES ('1029 Birchwood Dr','Burien','91364','Washington');
Insert into address (address,city, zip,state) VALUES ('1029 Birchwood Dr','Olympia','2300','Washington');
Insert into address (address,city, zip,state) VALUES ('1030 Ambush Dr.','Bury','V8Z 4N5','England');
Insert into address (address,city, zip,state) VALUES ('1032 Buena Vista','North Ryde','94014','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1032 Coats Road','Stoke-on-Trent','V8P','England');
Insert into address (address,city, zip,state) VALUES ('1035 Arguello Blvd.','San Diego','V2W 1W2','California');
Insert into address (address,city, zip,state) VALUES ('1036 Mason Dr','Port Orchard','94611','Washington');
Insert into address (address,city, zip,state) VALUES ('1039 Adelaide St.','Port Macquarie','97355','New South Wales');
Insert into address (address,city, zip,state) VALUES ('104 Hilltop Dr.','Concord','1597','California');
Insert into address (address,city, zip,state) VALUES ('1040 Greenbush Drive','Newton','V3A 4R2','British Columbia');
Insert into address (address,city, zip,state) VALUES ('1040 Northridge Road','Woodland Hills','','California');
Insert into address (address,city, zip,state) VALUES ('1042 Hooftrail Way','Newcastle','','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1046 Cloverleaf Circle','Shawnee','','British Columbia');
Insert into address (address,city, zip,state) VALUES ('1046 San Carlos Avenue','Colma','','California');
Insert into address (address,city, zip,state) VALUES ('1047 Las Quebradas Lane','Oak Bay','','British Columbia');
Insert into address (address,city, zip,state) VALUES ('1048 Burwood Way','Haney','','British Columbia');
Insert into address (address,city, zip,state) VALUES ('105 Woodruff Ln.','Oakland','','California');
Insert into address (address,city, zip,state) VALUES ('1050 Creed Ave','Lebanon','','Oregon');
Insert into address (address,city, zip,state) VALUES ('1050 Greenhills Circle','Lane Cove','','New South Wales');
Insert into address (address,city, zip,state) VALUES ('1050 Greenhills Circle','Langley','','British Columbia');
